# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class AddressSignals(BaseModel):
    """
    Local-part parsing insights produced during analysis. The service always returns this payload; when a specific signal is unavailable, the corresponding value falls back to `false` or an empty string.
    """ # noqa: E501
    tag_detected: StrictBool = Field(description="Indicates whether the local-part contains `+tag` sub-addressing. Default: false. Example: true.", alias="tagDetected")
    tag_value: StrictStr = Field(description="Raw tag contents following the plus sign. Empty string when a tag is not present or has no suffix. Default: empty string. Example: \"campaign-123\".", alias="tagValue")
    normalized_address: StrictStr = Field(description="Email rebuilt without the tag. Always lower-case. Default: empty string. Example: \"noreply@company.com\".", alias="normalizedAddress")
    is_role_address: StrictBool = Field(description="True when the local-part maps to a catalogued role inbox (e.g., support, sales, billing). Default: false. Example: true.", alias="isRoleAddress")
    role_type: StrictStr = Field(description="Role category slug. Empty string when `isRoleAddress` is false. Default: empty string. Example: \"support\".", alias="roleType")
    is_no_reply: StrictBool = Field(description="True when the local-part matches no-reply or do-not-reply patterns (multi-language aware). Default: false. Example: true.", alias="isNoReply")
    no_reply_pattern: StrictStr = Field(description="Canonical pattern matched when `isNoReply` is true (for example `noreply`, `no-responder`, `mailer-daemon`). Empty string when no pattern applies. Default: empty string. Example: \"noreply\".", alias="noReplyPattern")
    __properties: ClassVar[List[str]] = ["tagDetected", "tagValue", "normalizedAddress", "isRoleAddress", "roleType", "isNoReply", "noReplyPattern"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddressSignals from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddressSignals from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tagDetected": obj.get("tagDetected"),
            "tagValue": obj.get("tagValue"),
            "normalizedAddress": obj.get("normalizedAddress"),
            "isRoleAddress": obj.get("isRoleAddress"),
            "roleType": obj.get("roleType"),
            "isNoReply": obj.get("isNoReply"),
            "noReplyPattern": obj.get("noReplyPattern")
        })
        return _obj

