# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from fraud_intel_client.models.fraud_analyze_session_detections_inner import FraudAnalyzeSessionDetectionsInner
from fraud_intel_client.models.risk_report import RiskReport
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200ResponseSourcesSession(BaseModel):
    """
    Behavioral session intelligence derived from the Opportify frontend SDK token. Present when `opportifyToken` was supplied.
    """ # noqa: E501
    client_id: Optional[StrictStr] = Field(default=None, description="Persistent device fingerprint identifier.", alias="clientId")
    session_id: Optional[StrictStr] = Field(default=None, description="Session-scoped identifier for the current browser session.", alias="sessionId")
    fuuid: Optional[StrictStr] = Field(default=None, description="UUID of the form as stored in the session record (raw field name from the SDK).")
    token_age: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Age of the SDK-issued token in seconds at the time of submission.", alias="tokenAge")
    token_valid: Optional[StrictBool] = Field(default=None, description="Whether the token passed cryptographic verification.", alias="tokenValid")
    detections: Optional[List[FraudAnalyzeSessionDetectionsInner]] = Field(default=None, description="Behavioral detection results aggregated from the session and its associated event records, deduplicated by name. Each element is a name/value pair. Example detection names: hpot (honeypot triggered),…")
    score: Optional[StrictInt] = Field(default=None, description="Composite session risk score normalized to 200–1000. Present when behavioral analysis produced a session risk score.")
    level: Optional[StrictStr] = Field(default=None, description="Risk level derived from session behavioral analysis. Allowed values: lowest, low, medium, high, highest.")
    factors: Optional[List[StrictStr]] = Field(default=None, description="Factor codes contributing to the session risk score. Values follow the `session:factor-code` format.")
    event_count: Optional[StrictInt] = Field(default=None, description="Number of telemetry events recorded for this session.", alias="eventCount")
    risk_report: Optional[RiskReport] = Field(default=None, description="Risk report from session behavioral analysis.", alias="riskReport")
    __properties: ClassVar[List[str]] = ["clientId", "sessionId", "fuuid", "tokenAge", "tokenValid", "detections", "score", "level", "factors", "eventCount", "riskReport"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesSession from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in detections (list)
        _items = []
        if self.detections:
            for _item_detections in self.detections:
                if _item_detections:
                    _items.append(_item_detections.to_dict())
            _dict['detections'] = _items
        # override the default output from pydantic by calling `to_dict()` of risk_report
        if self.risk_report:
            _dict['riskReport'] = self.risk_report.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesSession from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clientId": obj.get("clientId"),
            "sessionId": obj.get("sessionId"),
            "fuuid": obj.get("fuuid"),
            "tokenAge": obj.get("tokenAge"),
            "tokenValid": obj.get("tokenValid"),
            "detections": [FraudAnalyzeSessionDetectionsInner.from_dict(_item) for _item in obj["detections"]] if obj.get("detections") is not None else None,
            "score": obj.get("score"),
            "level": obj.get("level"),
            "factors": obj.get("factors"),
            "eventCount": obj.get("eventCount"),
            "riskReport": RiskReport.from_dict(obj["riskReport"]) if obj.get("riskReport") is not None else None
        })
        return _obj

