# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from fraud_intel_client.models.analyze_fraud200_response_sources_content import AnalyzeFraud200ResponseSourcesContent
from fraud_intel_client.models.analyze_fraud200_response_sources_email import AnalyzeFraud200ResponseSourcesEmail
from fraud_intel_client.models.analyze_fraud200_response_sources_geo import AnalyzeFraud200ResponseSourcesGeo
from fraud_intel_client.models.analyze_fraud200_response_sources_ip import AnalyzeFraud200ResponseSourcesIp
from fraud_intel_client.models.analyze_fraud200_response_sources_session import AnalyzeFraud200ResponseSourcesSession
from fraud_intel_client.models.analyze_fraud200_response_sources_velocity import AnalyzeFraud200ResponseSourcesVelocity
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200ResponseSources(BaseModel):
    """
    Per-signal analysis results. `email` and `ip` are present only when the corresponding input field was supplied and omitted otherwise. `content`, `session`, `velocity`, and `geo` are always present as…
    """ # noqa: E501
    email: Optional[AnalyzeFraud200ResponseSourcesEmail] = None
    ip: Optional[AnalyzeFraud200ResponseSourcesIp] = None
    content: Optional[AnalyzeFraud200ResponseSourcesContent] = None
    session: Optional[AnalyzeFraud200ResponseSourcesSession] = None
    velocity: Optional[AnalyzeFraud200ResponseSourcesVelocity] = None
    geo: Optional[AnalyzeFraud200ResponseSourcesGeo] = None
    __properties: ClassVar[List[str]] = ["email", "ip", "content", "session", "velocity", "geo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSources from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of email
        if self.email:
            _dict['email'] = self.email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ip
        if self.ip:
            _dict['ip'] = self.ip.to_dict()
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['content'] = self.content.to_dict()
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        # override the default output from pydantic by calling `to_dict()` of velocity
        if self.velocity:
            _dict['velocity'] = self.velocity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of geo
        if self.geo:
            _dict['geo'] = self.geo.to_dict()
        # set to None if content (nullable) is None
        # and model_fields_set contains the field
        if self.content is None and "content" in self.model_fields_set:
            _dict['content'] = None

        # set to None if session (nullable) is None
        # and model_fields_set contains the field
        if self.session is None and "session" in self.model_fields_set:
            _dict['session'] = None

        # set to None if velocity (nullable) is None
        # and model_fields_set contains the field
        if self.velocity is None and "velocity" in self.model_fields_set:
            _dict['velocity'] = None

        # set to None if geo (nullable) is None
        # and model_fields_set contains the field
        if self.geo is None and "geo" in self.model_fields_set:
            _dict['geo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSources from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": AnalyzeFraud200ResponseSourcesEmail.from_dict(obj["email"]) if obj.get("email") is not None else None,
            "ip": AnalyzeFraud200ResponseSourcesIp.from_dict(obj["ip"]) if obj.get("ip") is not None else None,
            "content": AnalyzeFraud200ResponseSourcesContent.from_dict(obj["content"]) if obj.get("content") is not None else None,
            "session": AnalyzeFraud200ResponseSourcesSession.from_dict(obj["session"]) if obj.get("session") is not None else None,
            "velocity": AnalyzeFraud200ResponseSourcesVelocity.from_dict(obj["velocity"]) if obj.get("velocity") is not None else None,
            "geo": AnalyzeFraud200ResponseSourcesGeo.from_dict(obj["geo"]) if obj.get("geo") is not None else None
        })
        return _obj

