# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from fraud_intel_client.models.address_signals import AddressSignals
from fraud_intel_client.models.email_dns import EmailDNS
from fraud_intel_client.models.email_domain import EmailDomain
from fraud_intel_client.models.risk_report_email import RiskReportEmail
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200ResponseSourcesEmail(BaseModel):
    """
    Full Email Insights response. Present when `email` was supplied.
    """ # noqa: E501
    email_address: StrictStr = Field(description="Normalized email address returned by the service (always lower-case).", alias="emailAddress")
    email_provider: StrictStr = Field(description="Provider slug derived from the domain, or `unknown` when not classified.", alias="emailProvider")
    email_type: StrictStr = Field(description="Email classification based on provider and enrichment signals. Allowed values: `private`, `free`, `disposable`, `unknown`.", alias="emailType")
    is_deliverable: StrictStr = Field(description="Checks if the email address exists and is deliverable using SMTP handshake simulation. Allowed values: `yes`, `no`, `unknown`.", alias="isDeliverable")
    is_catch_all: StrictBool = Field(description="Determines if the email domain is configured as a catch-all.", alias="isCatchAll")
    is_mailbox_full: StrictBool = Field(description="Determines if the mailbox associated with the email is full.", alias="isMailboxFull")
    is_reachable: StrictBool = Field(description="Confirms if the email domain has valid MX DNS records using DNS lookup.", alias="isReachable")
    is_format_valid: StrictBool = Field(description="Indicates if the email address meets syntax validation rules.", alias="isFormatValid")
    email_correction: StrictStr = Field(description="The corrected email address when the system is highly confident about a typo or misspelling. Empty string when no correction is needed.", alias="emailCorrection")
    email_auto_corrected_from: Optional[StrictStr] = Field(default=None, description="The original email address before auto-correction was applied. Present only when auto-correction was applied.", alias="emailAutoCorrectedFrom")
    address_signals: AddressSignals = Field(description="Local-part parsing details for the analyzed address.", alias="addressSignals")
    email_dns: EmailDNS = Field(alias="emailDNS")
    risk_report: Optional[RiskReportEmail] = Field(default=None, description="Risk report from Email Insights analysis.", alias="riskReport")
    domain: Optional[EmailDomain] = Field(default=None, description="Domain summary derived from enrichment providers.")
    __properties: ClassVar[List[str]] = ["emailAddress", "emailProvider", "emailType", "isDeliverable", "isCatchAll", "isMailboxFull", "isReachable", "isFormatValid", "emailCorrection", "emailAutoCorrectedFrom", "addressSignals", "emailDNS", "riskReport", "domain"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesEmail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address_signals
        if self.address_signals:
            _dict['addressSignals'] = self.address_signals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of email_dns
        if self.email_dns:
            _dict['emailDNS'] = self.email_dns.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risk_report
        if self.risk_report:
            _dict['riskReport'] = self.risk_report.to_dict()
        # override the default output from pydantic by calling `to_dict()` of domain
        if self.domain:
            _dict['domain'] = self.domain.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesEmail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "emailAddress": obj.get("emailAddress"),
            "emailProvider": obj.get("emailProvider"),
            "emailType": obj.get("emailType"),
            "isDeliverable": obj.get("isDeliverable"),
            "isCatchAll": obj.get("isCatchAll"),
            "isMailboxFull": obj.get("isMailboxFull"),
            "isReachable": obj.get("isReachable"),
            "isFormatValid": obj.get("isFormatValid"),
            "emailCorrection": obj.get("emailCorrection"),
            "emailAutoCorrectedFrom": obj.get("emailAutoCorrectedFrom"),
            "addressSignals": AddressSignals.from_dict(obj["addressSignals"]) if obj.get("addressSignals") is not None else None,
            "emailDNS": EmailDNS.from_dict(obj["emailDNS"]) if obj.get("emailDNS") is not None else None,
            "riskReport": RiskReportEmail.from_dict(obj["riskReport"]) if obj.get("riskReport") is not None else None,
            "domain": EmailDomain.from_dict(obj["domain"]) if obj.get("domain") is not None else None
        })
        return _obj

