# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraudRequest(BaseModel):
    """
    AnalyzeFraudRequest
    """ # noqa: E501
    email: Optional[Annotated[str, Field(strict=True, max_length=320)]] = Field(default=None, description="Email address associated with the submission. At least one of `email` or `userIp` is required.")
    phone1: Optional[StrictStr] = Field(default=None, description="Primary phone number in E.164 format.")
    phone2: Optional[StrictStr] = Field(default=None, description="Secondary or alternate phone number in E.164 format.")
    user_ip: Optional[StrictStr] = Field(default=None, description="IPv4 or IPv6 address of the submitting user. At least one of `email` or `userIp` is required.", alias="userIp")
    first_name: Optional[StrictStr] = Field(default=None, description="First name of the submitter.", alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, description="Last name of the submitter.", alias="lastName")
    full_name: Optional[StrictStr] = Field(default=None, description="Full name of the submitter when first and last are not split.", alias="fullName")
    username: Optional[StrictStr] = Field(default=None, description="Requested username or handle.")
    company_name: Optional[StrictStr] = Field(default=None, description="Company or organization name provided by the submitter.", alias="companyName")
    website: Optional[StrictStr] = Field(default=None, description="Website URL provided by the submitter.")
    subject: Optional[StrictStr] = Field(default=None, description="Subject line for contact or support forms.")
    message: Optional[StrictStr] = Field(default=None, description="Free-text message body of the submission.")
    address1: Optional[StrictStr] = Field(default=None, description="Primary street address.")
    address2: Optional[StrictStr] = Field(default=None, description="Apartment, suite, or unit number.")
    city: Optional[StrictStr] = Field(default=None, description="City of the submitter.")
    region: Optional[StrictStr] = Field(default=None, description="State, province, or region code.")
    country: Optional[StrictStr] = Field(default=None, description="ISO 3166-1 alpha-2 country code.")
    postal_code: Optional[StrictStr] = Field(default=None, description="Postal or ZIP code.", alias="postalCode")
    origin: Optional[StrictStr] = Field(default=None, description="Hostname of the page where the form was submitted (hostname only — no protocol, path, or port). Required when `opportifyToken` is provided.")
    submission_type: Optional[StrictStr] = Field(default=None, description="Semantic type of the form being analyzed. Known values: registration, trial, contactForm, checkout, leadCapture, subscription, support. Custom values are accepted and stored but do not currently…", alias="submissionType")
    form_data: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary key-value map of additional form fields for advanced content analysis.", alias="formData")
    opportify_token: Optional[StrictStr] = Field(default=None, description="Token issued by the Opportify frontend SDK. Carries session fingerprint and behavioral signals. Required for session source analysis. This is distinct from the `x-opportify-token` API key header used…", alias="opportifyToken")
    opportify_form_uuid: Optional[StrictStr] = Field(default=None, description="UUID identifying the specific form configured in the Opportify dashboard.", alias="opportifyFormUUID")
    __properties: ClassVar[List[str]] = ["email", "phone1", "phone2", "userIp", "firstName", "lastName", "fullName", "username", "companyName", "website", "subject", "message", "address1", "address2", "city", "region", "country", "postalCode", "origin", "submissionType", "formData", "opportifyToken", "opportifyFormUUID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraudRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraudRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "phone1": obj.get("phone1"),
            "phone2": obj.get("phone2"),
            "userIp": obj.get("userIp"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "fullName": obj.get("fullName"),
            "username": obj.get("username"),
            "companyName": obj.get("companyName"),
            "website": obj.get("website"),
            "subject": obj.get("subject"),
            "message": obj.get("message"),
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "city": obj.get("city"),
            "region": obj.get("region"),
            "country": obj.get("country"),
            "postalCode": obj.get("postalCode"),
            "origin": obj.get("origin"),
            "submissionType": obj.get("submissionType"),
            "formData": obj.get("formData"),
            "opportifyToken": obj.get("opportifyToken"),
            "opportifyFormUUID": obj.get("opportifyFormUUID")
        })
        return _obj

