# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200ResponseSourcesGeoSignals(BaseModel):
    """
    ISO 3166-1 alpha-2 country codes from each geographic signal. `null` when the signal is unavailable.
    """ # noqa: E501
    ip_country: Optional[StrictStr] = Field(default=None, description="Country from IP geolocation.", alias="ipCountry")
    phone_country: Optional[StrictStr] = Field(default=None, description="Country from phone number registration data.", alias="phoneCountry")
    email_domain_country: Optional[StrictStr] = Field(default=None, description="Country inferred from email domain registration.", alias="emailDomainCountry")
    session_country: Optional[StrictStr] = Field(default=None, description="Country from the session source IP (behavioral data).", alias="sessionCountry")
    declared_country: Optional[StrictStr] = Field(default=None, description="Country from the `country` request field (ISO 3166-1 alpha-2).", alias="declaredCountry")
    __properties: ClassVar[List[str]] = ["ipCountry", "phoneCountry", "emailDomainCountry", "sessionCountry", "declaredCountry"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesGeoSignals from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ip_country (nullable) is None
        # and model_fields_set contains the field
        if self.ip_country is None and "ip_country" in self.model_fields_set:
            _dict['ipCountry'] = None

        # set to None if phone_country (nullable) is None
        # and model_fields_set contains the field
        if self.phone_country is None and "phone_country" in self.model_fields_set:
            _dict['phoneCountry'] = None

        # set to None if email_domain_country (nullable) is None
        # and model_fields_set contains the field
        if self.email_domain_country is None and "email_domain_country" in self.model_fields_set:
            _dict['emailDomainCountry'] = None

        # set to None if session_country (nullable) is None
        # and model_fields_set contains the field
        if self.session_country is None and "session_country" in self.model_fields_set:
            _dict['sessionCountry'] = None

        # set to None if declared_country (nullable) is None
        # and model_fields_set contains the field
        if self.declared_country is None and "declared_country" in self.model_fields_set:
            _dict['declaredCountry'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesGeoSignals from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ipCountry": obj.get("ipCountry"),
            "phoneCountry": obj.get("phoneCountry"),
            "emailDomainCountry": obj.get("emailDomainCountry"),
            "sessionCountry": obj.get("sessionCountry"),
            "declaredCountry": obj.get("declaredCountry")
        })
        return _obj

