# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List
from fraud_intel_client.models.analyze_fraud200_response_sources_geo_signals import AnalyzeFraud200ResponseSourcesGeoSignals
from fraud_intel_client.models.risk_report import RiskReport
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200ResponseSourcesGeo(BaseModel):
    """
    Cross-source geographic consistency check. Present when at least two geographic signals are available (IP geolocation, email domain country, declared `country` field, phone country, or session…
    """ # noqa: E501
    consistent: StrictBool = Field(description="True when all available geographic signals resolve to the same country code.")
    signals: AnalyzeFraud200ResponseSourcesGeoSignals
    risk_report: RiskReport = Field(description="Risk report for geographic consistency. Score is elevated when signals are inconsistent.", alias="riskReport")
    __properties: ClassVar[List[str]] = ["consistent", "signals", "riskReport"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesGeo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of signals
        if self.signals:
            _dict['signals'] = self.signals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risk_report
        if self.risk_report:
            _dict['riskReport'] = self.risk_report.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesGeo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "consistent": obj.get("consistent"),
            "signals": AnalyzeFraud200ResponseSourcesGeoSignals.from_dict(obj["signals"]) if obj.get("signals") is not None else None,
            "riskReport": RiskReport.from_dict(obj["riskReport"]) if obj.get("riskReport") is not None else None
        })
        return _obj

