# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from fraud_intel_client.models.analyze_fraud200_response_sources import AnalyzeFraud200ResponseSources
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200Response(BaseModel):
    """
    AnalyzeFraud200Response
    """ # noqa: E501
    score: StrictInt = Field(description="Composite fraud risk score normalized to 200–1000. Always present in the response.")
    level: StrictStr = Field(description="Human-readable risk level derived from `score`. Always present in the response. Allowed values: lowest, low, medium, high, highest.")
    factors: List[StrictStr] = Field(description="Top weighted risk factor codes contributing to the composite score. Always present in the response. Each code is prefixed with its source using the format `source:factor-code`. Possible source…")
    sources: AnalyzeFraud200ResponseSources
    __properties: ClassVar[List[str]] = ["score", "level", "factors", "sources"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sources
        if self.sources:
            _dict['sources'] = self.sources.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "score": obj.get("score"),
            "level": obj.get("level"),
            "factors": obj.get("factors"),
            "sources": AnalyzeFraud200ResponseSources.from_dict(obj["sources"]) if obj.get("sources") is not None else None
        })
        return _obj

