# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from fraud_intel_client.models.fraud_analyze_content_section import FraudAnalyzeContentSection
from fraud_intel_client.models.risk_report import RiskReport
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200ResponseSourcesContent(BaseModel):
    """
    Content analysis. `null` when none of `firstName`, `lastName`, `fullName`, `username`, `companyName`, `website`, `subject`, or `message` was supplied.
    """ # noqa: E501
    names: Optional[FraudAnalyzeContentSection] = Field(default=None, description="Analysis of name fields (firstName, lastName, fullName, username, companyName).")
    subject: Optional[FraudAnalyzeContentSection] = Field(default=None, description="Analysis of subject/title fields.")
    message: Optional[FraudAnalyzeContentSection] = Field(default=None, description="Analysis of message/body fields.")
    risk_report: Optional[RiskReport] = Field(default=None, description="Risk report for content signals. Present when content fields were supplied.", alias="riskReport")
    __properties: ClassVar[List[str]] = ["names", "subject", "message", "riskReport"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of names
        if self.names:
            _dict['names'] = self.names.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subject
        if self.subject:
            _dict['subject'] = self.subject.to_dict()
        # override the default output from pydantic by calling `to_dict()` of message
        if self.message:
            _dict['message'] = self.message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risk_report
        if self.risk_report:
            _dict['riskReport'] = self.risk_report.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "names": FraudAnalyzeContentSection.from_dict(obj["names"]) if obj.get("names") is not None else None,
            "subject": FraudAnalyzeContentSection.from_dict(obj["subject"]) if obj.get("subject") is not None else None,
            "message": FraudAnalyzeContentSection.from_dict(obj["message"]) if obj.get("message") is not None else None,
            "riskReport": RiskReport.from_dict(obj["riskReport"]) if obj.get("riskReport") is not None else None
        })
        return _obj

