# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from fraud_intel_client.models.fraud_velocity_window import FraudVelocityWindow
from fraud_intel_client.models.risk_report import RiskReport
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeFraud200ResponseSourcesVelocity(BaseModel):
    """
    Submission rate per identifier type over sliding windows. Always evaluated when identifiers are provided.
    """ # noqa: E501
    email_submissions: Optional[FraudVelocityWindow] = Field(alias="emailSubmissions")
    ip_submissions: Optional[FraudVelocityWindow] = Field(alias="ipSubmissions")
    phone_submissions: Optional[FraudVelocityWindow] = Field(alias="phoneSubmissions")
    anomaly: StrictBool = Field(description="True when any identifier's submission rate exceeds the configured anomaly threshold.")
    risk_report: RiskReport = Field(description="Risk report for velocity signals. Score is elevated when `anomaly` is `true`.", alias="riskReport")
    __properties: ClassVar[List[str]] = ["emailSubmissions", "ipSubmissions", "phoneSubmissions", "anomaly", "riskReport"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesVelocity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of email_submissions
        if self.email_submissions:
            _dict['emailSubmissions'] = self.email_submissions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ip_submissions
        if self.ip_submissions:
            _dict['ipSubmissions'] = self.ip_submissions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of phone_submissions
        if self.phone_submissions:
            _dict['phoneSubmissions'] = self.phone_submissions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risk_report
        if self.risk_report:
            _dict['riskReport'] = self.risk_report.to_dict()
        # set to None if email_submissions (nullable) is None
        # and model_fields_set contains the field
        if self.email_submissions is None and "email_submissions" in self.model_fields_set:
            _dict['emailSubmissions'] = None

        # set to None if ip_submissions (nullable) is None
        # and model_fields_set contains the field
        if self.ip_submissions is None and "ip_submissions" in self.model_fields_set:
            _dict['ipSubmissions'] = None

        # set to None if phone_submissions (nullable) is None
        # and model_fields_set contains the field
        if self.phone_submissions is None and "phone_submissions" in self.model_fields_set:
            _dict['phoneSubmissions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeFraud200ResponseSourcesVelocity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "emailSubmissions": FraudVelocityWindow.from_dict(obj["emailSubmissions"]) if obj.get("emailSubmissions") is not None else None,
            "ipSubmissions": FraudVelocityWindow.from_dict(obj["ipSubmissions"]) if obj.get("ipSubmissions") is not None else None,
            "phoneSubmissions": FraudVelocityWindow.from_dict(obj["phoneSubmissions"]) if obj.get("phoneSubmissions") is not None else None,
            "anomaly": obj.get("anomaly"),
            "riskReport": RiskReport.from_dict(obj["riskReport"]) if obj.get("riskReport") is not None else None
        })
        return _obj

