# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BlockListed(BaseModel):
    """
    The `BlockListed` object provides detailed information about whether an IP address is listed in known blocklists and related data.
    """ # noqa: E501
    is_block_listed: StrictBool = Field(description="Indicates if the IP is blocklisted in some of the known blocklist sources.", alias="isBlockListed")
    sources: StrictInt = Field(description="Number of blocklist sources.")
    active_reports: StrictInt = Field(description="Number of blocklist active reports for the given IP address. We constantly monitor and update this value as new reports are detected or resolved.", alias="activeReports")
    last_detected: Optional[StrictStr] = Field(default=None, description="Date and time of the last blocklist detection. ISO 8601 standard. Format: date-time. Example: \"2022-01-01T12:00:00Z\".", alias="lastDetected")
    __properties: ClassVar[List[str]] = ["isBlockListed", "sources", "activeReports", "lastDetected"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlockListed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlockListed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isBlockListed": obj.get("isBlockListed"),
            "sources": obj.get("sources"),
            "activeReports": obj.get("activeReports"),
            "lastDetected": obj.get("lastDetected")
        })
        return _obj

