# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class EmailDomain(BaseModel):
    """
    Summary of the domain-level enrichment returned when enrichment is available and not opted out via `enableDomainEnrichment`.
    """ # noqa: E501
    name: StrictStr = Field(description="Fully qualified domain name associated with the email. Default: empty string. Example: \"company.com\".")
    enrichment_available: StrictBool = Field(description="Indicates whether enrichment data was available at analysis time.", alias="enrichmentAvailable")
    creation_date: StrictStr = Field(description="Domain creation timestamp (ISO 8601). Returns an empty string when enrichment data is unavailable. Format: date-time. Example: \"2014-05-12T00:00:00Z\".", alias="creationDate")
    expiration_date: StrictStr = Field(description="Domain expiration timestamp (ISO 8601). Returns an empty string when enrichment data is unavailable. Format: date-time. Example: \"2026-05-11T23:59:59Z\".", alias="expirationDate")
    updated_date: StrictStr = Field(description="Last WHOIS update timestamp (ISO 8601). Returns an empty string when enrichment data is unavailable. Format: date-time. Example: \"2024-11-01T08:30:00Z\".", alias="updatedDate")
    age_years: StrictInt = Field(description="Domain age in whole years based on stored enrichment data. Returns 0 for domains younger than one year. Default: 0. Example: 11.", alias="ageYears")
    registrar: StrictStr = Field(description="Registrar recorded for the domain. Default: empty string. Example: \"Namecheap, Inc.\".")
    is_block_listed: StrictBool = Field(description="Indicates whether the domain appears in monitored blocklists. Default: false. Example: false.", alias="isBlockListed")
    mta_sts_status: StrictStr = Field(description="Status of the domain's MTA-STS configuration. Allowed values: `present`, `invalid`, `absent`, `unknown`. Default: `unknown`. Example: `present`.", alias="mtaStsStatus")
    bimi_status: StrictStr = Field(description="BIMI (Brand Indicators for Message Identification) status. Allowed values: `present`, `present-no-vmc`, `invalid`, `absent`, `unknown`. Default: `unknown`. Example: `present-no-vmc`.", alias="bimiStatus")
    has_vmc: StrictBool = Field(description="Indicates whether a Verified Mark Certificate is associated with the domain. Default: false. Example: false.", alias="hasVMC")
    a_record_valid: StrictBool = Field(description="Indicates whether the domain has valid A records. Default: false. Example: true.", alias="aRecordValid")
    a_record_reverse_host: StrictStr = Field(description="Reverse hostname observed for the A record when available. Empty string when no reverse mapping is returned. Default: empty string. Example: \"reverse.company.com\".", alias="aRecordReverseHost")
    ssl_valid: StrictBool = Field(description="Indicates whether the domain serves a valid SSL certificate on common endpoints. Default: false. Example: true.", alias="sslValid")
    __properties: ClassVar[List[str]] = ["name", "enrichmentAvailable", "creationDate", "expirationDate", "updatedDate", "ageYears", "registrar", "isBlockListed", "mtaStsStatus", "bimiStatus", "hasVMC", "aRecordValid", "aRecordReverseHost", "sslValid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailDomain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailDomain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "enrichmentAvailable": obj.get("enrichmentAvailable"),
            "creationDate": obj.get("creationDate"),
            "expirationDate": obj.get("expirationDate"),
            "updatedDate": obj.get("updatedDate"),
            "ageYears": obj.get("ageYears"),
            "registrar": obj.get("registrar"),
            "isBlockListed": obj.get("isBlockListed"),
            "mtaStsStatus": obj.get("mtaStsStatus"),
            "bimiStatus": obj.get("bimiStatus"),
            "hasVMC": obj.get("hasVMC"),
            "aRecordValid": obj.get("aRecordValid"),
            "aRecordReverseHost": obj.get("aRecordReverseHost"),
            "sslValid": obj.get("sslValid")
        })
        return _obj

