# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class EmailDNS(BaseModel):
    """
    DNS details for an email address domain.
    """ # noqa: E501
    mx: List[StrictStr] = Field(description="Mail exchange records for the domain formatted as \"<priority> <hostname>\". Records are sorted ascending by numeric priority before responding. Default: empty array. Example: [\"0 mx1.example.com\", \"10…")
    spf_valid: StrictBool = Field(description="Indicates whether SPF validation succeeded for the domain. Default: false. Example: true.", alias="spfValid")
    dkim_configured: StrictBool = Field(description="Indicates whether DKIM selectors are configured for the domain. Default: false. Example: true.", alias="dkimConfigured")
    dmarc_valid: StrictBool = Field(description="Indicates whether a valid DMARC policy is present for the domain. Default: false. Example: false.", alias="dmarcValid")
    mx_relay: StrictStr = Field(description="Primary MX relay hostname identified during analysis. Default: empty string. Example: \"mx1.example.com\".", alias="mxRelay")
    mx_relay_category: StrictStr = Field(description="Categorization of the MX relay (provider slug or classification when available). Default: empty string. Example: \"google\".", alias="mxRelayCategory")
    __properties: ClassVar[List[str]] = ["mx", "spfValid", "dkimConfigured", "dmarcValid", "mxRelay", "mxRelayCategory"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailDNS from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailDNS from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mx": obj.get("mx"),
            "spfValid": obj.get("spfValid"),
            "dkimConfigured": obj.get("dkimConfigured"),
            "dmarcValid": obj.get("dmarcValid"),
            "mxRelay": obj.get("mxRelay"),
            "mxRelayCategory": obj.get("mxRelayCategory")
        })
        return _obj

