# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FraudVelocityWindow(BaseModel):
    """
    Submission counts for a single identifier type over four sliding time windows.
    """ # noqa: E501
    last60s: Optional[StrictInt] = Field(default=None, description="Number of submissions seen for this identifier in the last 60 seconds.")
    last300s: Optional[StrictInt] = Field(default=None, description="Number of submissions seen for this identifier in the last 5 minutes.")
    last3600s: Optional[StrictInt] = Field(default=None, description="Number of submissions seen for this identifier in the last hour.")
    last86400s: Optional[StrictInt] = Field(default=None, description="Number of submissions seen for this identifier in the last 24 hours.")
    __properties: ClassVar[List[str]] = ["last60s", "last300s", "last3600s", "last86400s"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FraudVelocityWindow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FraudVelocityWindow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "last60s": obj.get("last60s"),
            "last300s": obj.get("last300s"),
            "last3600s": obj.get("last3600s"),
            "last86400s": obj.get("last86400s")
        })
        return _obj

