# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class FraudAnalyzeContentSection(BaseModel):
    """
    Analysis results for a single content section (names, subject, or message).
    """ # noqa: E501
    gibberish_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gibberish probability score between 0 and 1.", alias="gibberishScore")
    is_gibberish: Optional[StrictBool] = Field(default=None, description="True when the text appears synthetically generated or incoherent.", alias="isGibberish")
    spam_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Spam probability score between 0 and 1. Present for subject and message sections.", alias="spamScore")
    is_spam: Optional[StrictBool] = Field(default=None, description="True when the content matches known spam patterns. Present for subject and message sections.", alias="isSpam")
    language: Optional[StrictStr] = Field(default=None, description="Detected language of the text content (BCP 47 tag). Present when language detection is possible.")
    __properties: ClassVar[List[str]] = ["gibberishScore", "isGibberish", "spamScore", "isSpam", "language"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FraudAnalyzeContentSection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FraudAnalyzeContentSection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gibberishScore": obj.get("gibberishScore"),
            "isGibberish": obj.get("isGibberish"),
            "spamScore": obj.get("spamScore"),
            "isSpam": obj.get("isSpam"),
            "language": obj.get("language")
        })
        return _obj

