# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Geo(BaseModel):
    """
    Geolocation details are derived by analyzing the provided IP address using data aggregated from a wide range of sources, both official and unofficial (such as user-generated data, open-source, or…
    """ # noqa: E501
    continent: Optional[StrictStr] = Field(default=None, description="Name of the continent. Normalized as \"Title Case\".")
    country_code: Optional[StrictStr] = Field(default=None, description="ISO 3166-1 alpha-2 country code.", alias="countryCode")
    country_name: Optional[StrictStr] = Field(default=None, description="Full name of the country. Normalized as \"Title Case\".", alias="countryName")
    country_short_name: Optional[StrictStr] = Field(default=None, description="ISO 3166-1 English short version. Normalized as \"Title Case\".", alias="countryShortName")
    city: Optional[StrictStr] = Field(default=None, description="Name of the city. Normalized as \"Title Case\".")
    currency_code: Optional[StrictStr] = Field(default=None, description="ISO 4217 currency code.", alias="currencyCode")
    domain_extension: Optional[StrictStr] = Field(default=None, description="Top-level domain (TLD) for the country. 63 characters limit. IANA / ICANN defined.", alias="domainExtension")
    languages: Optional[StrictStr] = Field(default=None, description="List of languages spoken in the country separated by commas. (BCP 47 (Best Current Practice 47))")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Latitude coordinate.")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Longitude coordinate.")
    postal_code: Optional[StrictStr] = Field(default=None, description="Postal code. Normalized to all capital letters when applicable.", alias="postalCode")
    phone_int_code: Optional[StrictStr] = Field(default=None, description="International dialing code.", alias="phoneIntCode")
    region: Optional[StrictStr] = Field(default=None, description="Name of the region, province, or state. Normalized as \"Title Case\".")
    timezone: Optional[StrictStr] = Field(default=None, description="Timezone in IANA format.")
    __properties: ClassVar[List[str]] = ["continent", "countryCode", "countryName", "countryShortName", "city", "currencyCode", "domainExtension", "languages", "latitude", "longitude", "postalCode", "phoneIntCode", "region", "timezone"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Geo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Geo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "continent": obj.get("continent"),
            "countryCode": obj.get("countryCode"),
            "countryName": obj.get("countryName"),
            "countryShortName": obj.get("countryShortName"),
            "city": obj.get("city"),
            "currencyCode": obj.get("currencyCode"),
            "domainExtension": obj.get("domainExtension"),
            "languages": obj.get("languages"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "postalCode": obj.get("postalCode"),
            "phoneIntCode": obj.get("phoneIntCode"),
            "region": obj.get("region"),
            "timezone": obj.get("timezone")
        })
        return _obj

