# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Organization(BaseModel):
    """
    Organization details for an IP address.
    """ # noqa: E501
    org_id: Optional[StrictStr] = Field(default=None, description="Organization ID.", alias="orgId")
    org_name: Optional[StrictStr] = Field(default=None, description="Organization name.", alias="orgName")
    org_type: Optional[StrictStr] = Field(default=None, description="Organization type.", alias="orgType")
    descr: Optional[List[StrictStr]] = Field(default=None, description="Organization description. It might return different values based on the data source. Some provide ownership, address, others provide a more abstract description. Our system tries to sanitize removing…")
    address: Optional[List[StrictStr]] = Field(default=None, description="Organization address details. No standard address format is guaranteed.")
    country: Optional[StrictStr] = Field(default=None, description="Country code of the organization with 2 digits. (ISO 3166-1 alpha-2)")
    phone: Optional[List[StrictStr]] = Field(default=None, description="Contact phone numbers.")
    fax: Optional[List[StrictStr]] = Field(default=None, description="Contact fax numbers.")
    email: Optional[List[StrictStr]] = Field(default=None, description="Previously sanitized and validated contact email addresses always in lower case.")
    __properties: ClassVar[List[str]] = ["orgId", "orgName", "orgType", "descr", "address", "country", "phone", "fax", "email"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Organization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Organization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orgId": obj.get("orgId"),
            "orgName": obj.get("orgName"),
            "orgType": obj.get("orgType"),
            "descr": obj.get("descr"),
            "address": obj.get("address"),
            "country": obj.get("country"),
            "phone": obj.get("phone"),
            "fax": obj.get("fax"),
            "email": obj.get("email")
        })
        return _obj

