# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TrustedProvider(BaseModel):
    """
    Details of trusted providers for an IP address.
    """ # noqa: E501
    is_known_provider: StrictBool = Field(description="Indicates if the IP belongs to a trusted provider.", alias="isKnownProvider")
    provider: Optional[StrictStr] = Field(default=None, description="Name of the trusted provider.")
    provider_type: Optional[StrictStr] = Field(default=None, description="Type of the trusted provider.", alias="providerType")
    description: Optional[StrictStr] = Field(default=None, description="Provider a short description.")
    __properties: ClassVar[List[str]] = ["isKnownProvider", "provider", "providerType", "description"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrustedProvider from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrustedProvider from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isKnownProvider": obj.get("isKnownProvider"),
            "provider": obj.get("provider"),
            "providerType": obj.get("providerType"),
            "description": obj.get("description")
        })
        return _obj

