# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.forbidden import FORBIDDEN
from openapi_client.models.internalerror import INTERNALERROR
from openapi_client.models.invalidplan import INVALIDPLAN
from openapi_client.models.invalidtoken import INVALIDTOKEN
from openapi_client.models.malformedrequest1 import MALFORMEDREQUEST1
from openapi_client.models.quotaexceeded import QUOTAEXCEEDED
from openapi_client.models.toomanyrequests import TOOMANYREQUESTS
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ANALYZEEMAIL403RESPONSE_ONE_OF_SCHEMAS = ["FORBIDDEN", "INTERNALERROR", "INVALIDPLAN", "INVALIDTOKEN", "MALFORMEDREQUEST1", "QUOTAEXCEEDED", "TOOMANYREQUESTS"]

class AnalyzeEmail403Response(BaseModel):
    """
    AnalyzeEmail403Response
    """
    # data type: MALFORMEDREQUEST1
    oneof_schema_1_validator: Optional[MALFORMEDREQUEST1] = None
    # data type: INVALIDTOKEN
    oneof_schema_2_validator: Optional[INVALIDTOKEN] = None
    # data type: INVALIDPLAN
    oneof_schema_3_validator: Optional[INVALIDPLAN] = None
    # data type: FORBIDDEN
    oneof_schema_4_validator: Optional[FORBIDDEN] = None
    # data type: TOOMANYREQUESTS
    oneof_schema_5_validator: Optional[TOOMANYREQUESTS] = None
    # data type: INTERNALERROR
    oneof_schema_6_validator: Optional[INTERNALERROR] = None
    # data type: QUOTAEXCEEDED
    oneof_schema_7_validator: Optional[QUOTAEXCEEDED] = None
    actual_instance: Optional[Union[FORBIDDEN, INTERNALERROR, INVALIDPLAN, INVALIDTOKEN, MALFORMEDREQUEST1, QUOTAEXCEEDED, TOOMANYREQUESTS]] = None
    one_of_schemas: Set[str] = { "FORBIDDEN", "INTERNALERROR", "INVALIDPLAN", "INVALIDTOKEN", "MALFORMEDREQUEST1", "QUOTAEXCEEDED", "TOOMANYREQUESTS" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AnalyzeEmail403Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: MALFORMEDREQUEST1
        if not isinstance(v, MALFORMEDREQUEST1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MALFORMEDREQUEST1`")
        else:
            match += 1
        # validate data type: INVALIDTOKEN
        if not isinstance(v, INVALIDTOKEN):
            error_messages.append(f"Error! Input type `{type(v)}` is not `INVALIDTOKEN`")
        else:
            match += 1
        # validate data type: INVALIDPLAN
        if not isinstance(v, INVALIDPLAN):
            error_messages.append(f"Error! Input type `{type(v)}` is not `INVALIDPLAN`")
        else:
            match += 1
        # validate data type: FORBIDDEN
        if not isinstance(v, FORBIDDEN):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FORBIDDEN`")
        else:
            match += 1
        # validate data type: TOOMANYREQUESTS
        if not isinstance(v, TOOMANYREQUESTS):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TOOMANYREQUESTS`")
        else:
            match += 1
        # validate data type: INTERNALERROR
        if not isinstance(v, INTERNALERROR):
            error_messages.append(f"Error! Input type `{type(v)}` is not `INTERNALERROR`")
        else:
            match += 1
        # validate data type: QUOTAEXCEEDED
        if not isinstance(v, QUOTAEXCEEDED):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QUOTAEXCEEDED`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AnalyzeEmail403Response with oneOf schemas: FORBIDDEN, INTERNALERROR, INVALIDPLAN, INVALIDTOKEN, MALFORMEDREQUEST1, QUOTAEXCEEDED, TOOMANYREQUESTS. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AnalyzeEmail403Response with oneOf schemas: FORBIDDEN, INTERNALERROR, INVALIDPLAN, INVALIDTOKEN, MALFORMEDREQUEST1, QUOTAEXCEEDED, TOOMANYREQUESTS. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into MALFORMEDREQUEST1
        try:
            instance.actual_instance = MALFORMEDREQUEST1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into INVALIDTOKEN
        try:
            instance.actual_instance = INVALIDTOKEN.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into INVALIDPLAN
        try:
            instance.actual_instance = INVALIDPLAN.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FORBIDDEN
        try:
            instance.actual_instance = FORBIDDEN.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TOOMANYREQUESTS
        try:
            instance.actual_instance = TOOMANYREQUESTS.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into INTERNALERROR
        try:
            instance.actual_instance = INTERNALERROR.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QUOTAEXCEEDED
        try:
            instance.actual_instance = QUOTAEXCEEDED.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AnalyzeEmail403Response with oneOf schemas: FORBIDDEN, INTERNALERROR, INVALIDPLAN, INVALIDTOKEN, MALFORMEDREQUEST1, QUOTAEXCEEDED, TOOMANYREQUESTS. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AnalyzeEmail403Response with oneOf schemas: FORBIDDEN, INTERNALERROR, INVALIDPLAN, INVALIDTOKEN, MALFORMEDREQUEST1, QUOTAEXCEEDED, TOOMANYREQUESTS. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FORBIDDEN, INTERNALERROR, INVALIDPLAN, INVALIDTOKEN, MALFORMEDREQUEST1, QUOTAEXCEEDED, TOOMANYREQUESTS]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

