# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_client.models.block_listed import BlockListed
from openapi_client.models.geo import Geo
from openapi_client.models.risk_report_ip import RiskReportIp
from openapi_client.models.trusted_provider import TrustedProvider
from openapi_client.models.whois import Whois
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeIp200Response(BaseModel):
    """
    AnalyzeIp200Response
    """ # noqa: E501
    ip_address: StrictStr = Field(description="The analyzed IP address.", alias="ipAddress")
    ip_address_number: StrictInt = Field(description="Numeric representation of the IP address.", alias="ipAddressNumber")
    ip_type: StrictStr = Field(description="Type of the IP address (IPv4 or IPv6).", alias="ipType")
    ip_cidr: StrictStr = Field(description="CIDR notation of the IP address.", alias="ipCidr")
    connection_type: StrictStr = Field(description="The **connectionType** element provides information about the type of connection associated with a given IP address. Our system employs a **dynamic and evolving approach**, leveraging multiple data…", alias="connectionType")
    host_reverse: StrictStr = Field(description="Real time reverse DNS lookup result for the IP address.", alias="hostReverse")
    geo: Geo
    whois: Whois
    trusted_provider: TrustedProvider = Field(alias="trustedProvider")
    blocklisted: BlockListed
    risk_report: RiskReportIp = Field(alias="riskReport")
    __properties: ClassVar[List[str]] = ["ipAddress", "ipAddressNumber", "ipType", "ipCidr", "connectionType", "hostReverse", "geo", "whois", "trustedProvider", "blocklisted", "riskReport"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeIp200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of geo
        if self.geo:
            _dict['geo'] = self.geo.to_dict()
        # override the default output from pydantic by calling `to_dict()` of whois
        if self.whois:
            _dict['whois'] = self.whois.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trusted_provider
        if self.trusted_provider:
            _dict['trustedProvider'] = self.trusted_provider.to_dict()
        # override the default output from pydantic by calling `to_dict()` of blocklisted
        if self.blocklisted:
            _dict['blocklisted'] = self.blocklisted.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risk_report
        if self.risk_report:
            _dict['riskReport'] = self.risk_report.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeIp200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ipAddress": obj.get("ipAddress"),
            "ipAddressNumber": obj.get("ipAddressNumber"),
            "ipType": obj.get("ipType"),
            "ipCidr": obj.get("ipCidr"),
            "connectionType": obj.get("connectionType"),
            "hostReverse": obj.get("hostReverse"),
            "geo": Geo.from_dict(obj["geo"]) if obj.get("geo") is not None else None,
            "whois": Whois.from_dict(obj["whois"]) if obj.get("whois") is not None else None,
            "trustedProvider": TrustedProvider.from_dict(obj["trustedProvider"]) if obj.get("trustedProvider") is not None else None,
            "blocklisted": BlockListed.from_dict(obj["blocklisted"]) if obj.get("blocklisted") is not None else None,
            "riskReport": RiskReportIp.from_dict(obj["riskReport"]) if obj.get("riskReport") is not None else None
        })
        return _obj

