# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeEmailRequest(BaseModel):
    """
    AnalyzeEmailRequest
    """ # noqa: E501
    email: Annotated[str, Field(strict=True, max_length=320)] = Field(description="The email address to validate.")
    enable_ai: Optional[StrictBool] = Field(default=None, description="Enable AI-driven risk analysis. Optional; defaults to `true`.", alias="enableAI")
    enable_auto_correction: Optional[StrictBool] = Field(default=None, description="Controls email auto-correction behavior. Default: `false`.", alias="enableAutoCorrection")
    enable_domain_enrichment: Optional[StrictBool] = Field(default=None, description="Include domain-level enrichment details. Optional; defaults to `true`. Set to `false` to omit the `domain` block even when the data exists.", alias="enableDomainEnrichment")
    __properties: ClassVar[List[str]] = ["email", "enableAI", "enableAutoCorrection", "enableDomainEnrichment"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeEmailRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeEmailRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "enableAI": obj.get("enableAI"),
            "enableAutoCorrection": obj.get("enableAutoCorrection"),
            "enableDomainEnrichment": obj.get("enableDomainEnrichment")
        })
        return _obj

