# coding: utf-8
# Auto-generated by OpenAPI Generator. Do not edit manually.

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.abuse_contact import AbuseContact
from openapi_client.models.admin_contact import AdminContact
from openapi_client.models.asn import Asn
from openapi_client.models.organization import Organization
from openapi_client.models.tech_contact import TechContact
from typing import Optional, Set
from typing_extensions import Self

class Whois(BaseModel):
    """
    This object provides sanitized and normalized WHOIS information for an IP address, including details about the Regional Internet Registry (RIR), Autonomous System Number (ASN), organization, and…
    """ # noqa: E501
    rir: Optional[StrictStr] = Field(default=None, description="Regional Internet Registry managing the IP.")
    asn: Optional[Asn] = None
    organization: Optional[Organization] = None
    abuse_contact: Optional[AbuseContact] = Field(default=None, alias="abuseContact")
    admin_contact: Optional[AdminContact] = Field(default=None, alias="adminContact")
    tech_contact: Optional[TechContact] = Field(default=None, alias="techContact")
    __properties: ClassVar[List[str]] = ["rir", "asn", "organization", "abuseContact", "adminContact", "techContact"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Whois from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of asn
        if self.asn:
            _dict['asn'] = self.asn.to_dict()
        # override the default output from pydantic by calling `to_dict()` of organization
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        # override the default output from pydantic by calling `to_dict()` of abuse_contact
        if self.abuse_contact:
            _dict['abuseContact'] = self.abuse_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of admin_contact
        if self.admin_contact:
            _dict['adminContact'] = self.admin_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tech_contact
        if self.tech_contact:
            _dict['techContact'] = self.tech_contact.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Whois from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rir": obj.get("rir"),
            "asn": Asn.from_dict(obj["asn"]) if obj.get("asn") is not None else None,
            "organization": Organization.from_dict(obj["organization"]) if obj.get("organization") is not None else None,
            "abuseContact": AbuseContact.from_dict(obj["abuseContact"]) if obj.get("abuseContact") is not None else None,
            "adminContact": AdminContact.from_dict(obj["adminContact"]) if obj.get("adminContact") is not None else None,
            "techContact": TechContact.from_dict(obj["techContact"]) if obj.get("techContact") is not None else None
        })
        return _obj

