name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  release-drafter:
    uses: opportify/.github/.github/workflows/release-drafter.yml@main
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
